url: "https://paulfinch.github.io"
repository:  "paulfinch/paulfinch.github.io"

excerpt_separator: "<!--more-->"

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed

collections:
  category:
    output: true
    permalink: /:collection/:name/index.html

defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

include:
  - _pages

tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty