title: PaulFinch
logo: default.png
description: Welcome to P4P3RSTR33T


#-------------------------------
# Author Settings
author:
  name: PaulFinch
  image: user.png
  say-hello: Hi, I am <strong>PaulFinch</strong>
  bio: I am root
