#-------------------------------
# General Site Settings
title: PaulFinch
logo: logo.png
description: Building Stuff Since [1983]
email: p4ulf1nch@gmail.com


#-------------------------------
# Author Settings
author:
  name: PaulFinch
  image: user.png
  say-hello: Hi, I'm <strong>PaulFinch</strong>
  bio: <strong>[ System Engineer ]</strong> && <strong>[ Time Traveller ]</strong>


#-------------------------------
# Contact links
twitter: https://twitter.com/_PaulFinch_
github: https://github.com/paulfinch/
